app:
  listen:
    host: 0.0.0.0
    port: 8000
  logging:
    destination: /home/pi/dev/logs/sensorkit-monitor.log
    log-level: debug
    format: '%(levelname)s %(asctime)s : %(message)s'
  metrics:
    encoding: prometheus
    labels:
      room: office
      version: 0.0.1
sensorkit:
  env:
    indoors: true
  virtual-devices:
    static-altitude:
      type: meter
      module: .virtuals.static
      builder: StaticBuilder
      capabilities:
        - altitude
      args:
        values:
          altitude:
            value: 1688
            units: m
    open-meteo-current:
      type: meter
      module: .virtuals.openmeteo
      builder: OpenMeteoCurrentBuilder
      capabilities:
        #- temperature
        #- relative_humidity
        #- rain
        #- showers
        - pressure_msl
        - temperature
        - relative_humidity
      args:
        interval: PT1M
        params:
          longitude: -105.1230315
          latitude: 39.7592537
          timezone: America/Denver
  calibrations:
    bmp390:
      - measurement: pressure_msl
        target:
          property: sea_level_pressure
          where: real # or on the object interface 'abstract'
        source:
          device: open-meteo-current
        policy:
          aggregation: average
          interval: PT1M
    scd41:
      - measurement: altitude
        target:
          propery: altitude
          where: real
        source:
          device: static-altitude
        policy:
          aggregation: average
          interval: oneshot
      - measurement: pressure
        target:
          method: set_ambient_pressure
          where: real
        source:
          device: bmp390
        policy:
          aggregation: average
          interval: PT1M
