sensorkit:
  env:
    indoors: true
  sensors:
    - selectors:
        name: tsl2591
        address: 0x29
      reset_at_exit: true
      parameters:
        - property: persist
          value: 5
        - property: threshold_high
          value: 20000
        - property: threshold_low
          value: 15000
    - selectors:
        name: scd41
      parameters:
        - property: altitude
          value: 1688
  virtual-devices:
    #static-altitude:
    #  type: meter
    #  module: .virtuals.static
    #  builder: StaticBuilder
    #  capabilities:
    #    - altitude
    #  args:
    #    values:
    #      altitude:
    #        value: 1688
    #        units: m
    open-meteo-current:
      type: meter
      module: .virtuals.openmeteo
      builder: OpenMeteoCurrentBuilder
      capabilities:
        #- temperature
        #- relative_humidity
        #- rain
        #- showers
        - pressure_msl
        - temperature
        - relative_humidity
      args:
        interval: PT1M
        params:
          longitude: -105.1230315
          latitude: 39.7592537
          timezone: America/Denver
  calibrations:
    bmp390:
      - measurement: pressure_msl
        target:
          property: sea_level_pressure
          where: real # or on the object interface 'abstract'
        source:
          virtual: open-meteo-current
        policy:
          aggregation: average
          interval: PT1M
    scd41:
      #  - measurement: altitude
      #  target:
      #    property: altitude
      #    where: real
      #  source:
      #    virtual: static-altitude
      #  policy:
      #    aggregation: first
      #    interval: oneshot
      - measurement: pressure
        target:
          method: set_ambient_pressure
          where: real
        source:
          meter: bmp390
        policy:
          aggregation: average
          type: int
          interval: PT1M
